from sqlalchemy import (
    Boolean,
    Float,
    Column,
    ForeignKey,
    Integer,
    Date,
    BigInteger,
    String,
    UniqueConstraint,
)
from sqlalchemy.orm import relationship
from .database import Base


class Bundesrepublik(Base):
    __tablename__ = "bundesrepublik"
    ID = Column(Integer, primary_key=True, index=True)

    Flaeche = Column(Float)
    # Dichte = Column(Float)
    Einwohner = Column(Integer)
    Einwohner_AG_A00_A04 = Column(Integer)
    Einwohner_AG_A05_A14 = Column(Integer)
    Einwohner_AG_A15_A34 = Column(Integer)
    Einwohner_AG_A35_A59 = Column(Integer)
    Einwohner_AG_A60_A79 = Column(Integer)
    Einwohner_AG_A80Plus = Column(Integer)

    # down
    Bundeslaender = relationship("Bundesland", back_populates="Bundesrepublik")
    Daten = relationship("Bundesrepublik_Daten", back_populates="Bundesrepublik")

class Bundesrepublik_Daten(Base):
    __tablename__ = "bundesrepublik_daten"
    ID = Column(Integer, primary_key=True, index=True)

    DatenstandTag = Column(Integer)
    Datum = Column(Date, index=True)

    # IdLandkreis= Column(Integer)
    # Landkreis= Column(String)
    # LandkreisTyp= Column(String)
    # IdBundesland= Column(Integer)
    # Bundesland= Column(String)
    # Flaeche= Column(Float)
    MeldeTag_AnzahlFallNeu = Column(Integer)
    MeldeTag_AnzahlFall = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu = Column(Integer)
    MeldeTag_AnzahlTodesfall = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFall = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfall = Column(Integer)
    AnzahlFall = Column(Integer)
    AnzahlFallNeu = Column(Integer)
    AnzahlTodesfall = Column(Integer)
    AnzahlTodesfallNeu = Column(Integer)
    AnzahlGenesen = Column(Integer)
    AnzahlGenesenNeu = Column(Integer)
    PublikationsdauerFallNeu_Min = Column(Integer)
    PublikationsdauerFallNeu_Max = Column(Integer)
    PublikationsdauerFallNeu_Schnitt = Column(Float)
    PublikationsdauerFallNeu_Median = Column(Float)
    PublikationsdauerFallNeu_StdAbw = Column(Float)
    PublikationsdauerFallNeu_Fallbasis = Column(Integer)
    DatenstandTag_Max = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A00_A04 = Column(Integer)
    MeldeTag_AnzahlFall_AG_A00_A04 = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A00_A04 = Column(Integer)
    MeldeTag_AnzahlTodesfall_AG_A00_A04 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A00_A04 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFall_AG_A00_A04 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A00_A04 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfall_AG_A00_A04 = Column(Integer)
    AnzahlFall_AG_A00_A04 = Column(Integer)
    AnzahlFallNeu_AG_A00_A04 = Column(Integer)
    AnzahlTodesfall_AG_A00_A04 = Column(Integer)
    AnzahlTodesfallNeu_AG_A00_A04 = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A05_A14 = Column(Integer)
    MeldeTag_AnzahlFall_AG_A05_A14 = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A05_A14 = Column(Integer)
    MeldeTag_AnzahlTodesfall_AG_A05_A14 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A05_A14 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFall_AG_A05_A14 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A05_A14 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfall_AG_A05_A14 = Column(Integer)
    AnzahlFall_AG_A05_A14 = Column(Integer)
    AnzahlFallNeu_AG_A05_A14 = Column(Integer)
    AnzahlTodesfall_AG_A05_A14 = Column(Integer)
    AnzahlTodesfallNeu_AG_A05_A14 = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A15_A34 = Column(Integer)
    MeldeTag_AnzahlFall_AG_A15_A34 = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A15_A34 = Column(Integer)
    MeldeTag_AnzahlTodesfall_AG_A15_A34 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A15_A34 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFall_AG_A15_A34 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A15_A34 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfall_AG_A15_A34 = Column(Integer)
    AnzahlFall_AG_A15_A34 = Column(Integer)
    AnzahlFallNeu_AG_A15_A34 = Column(Integer)
    AnzahlTodesfall_AG_A15_A34 = Column(Integer)
    AnzahlTodesfallNeu_AG_A15_A34 = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A35_A59 = Column(Integer)
    MeldeTag_AnzahlFall_AG_A35_A59 = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A35_A59 = Column(Integer)
    MeldeTag_AnzahlTodesfall_AG_A35_A59 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A35_A59 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFall_AG_A35_A59 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A35_A59 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfall_AG_A35_A59 = Column(Integer)
    AnzahlFall_AG_A35_A59 = Column(Integer)
    AnzahlFallNeu_AG_A35_A59 = Column(Integer)
    AnzahlTodesfall_AG_A35_A59 = Column(Integer)
    AnzahlTodesfallNeu_AG_A35_A59 = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A60_A79 = Column(Integer)
    MeldeTag_AnzahlFall_AG_A60_A79 = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A60_A79 = Column(Integer)
    MeldeTag_AnzahlTodesfall_AG_A60_A79 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A60_A79 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFall_AG_A60_A79 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A60_A79 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfall_AG_A60_A79 = Column(Integer)
    AnzahlFall_AG_A60_A79 = Column(Integer)
    AnzahlFallNeu_AG_A60_A79 = Column(Integer)
    AnzahlTodesfall_AG_A60_A79 = Column(Integer)
    AnzahlTodesfallNeu_AG_A60_A79 = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A80Plus = Column(Integer)
    MeldeTag_AnzahlFall_AG_A80Plus = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A80Plus = Column(Integer)
    MeldeTag_AnzahlTodesfall_AG_A80Plus = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A80Plus = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFall_AG_A80Plus = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A80Plus = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfall_AG_A80Plus = Column(Integer)

    AnzahlFall_AG_A80Plus = Column(Integer)
    AnzahlFallNeu_AG_A80Plus = Column(Integer)
    AnzahlTodesfall_AG_A80Plus = Column(Integer)
    AnzahlTodesfallNeu_AG_A80Plus = Column(Integer)
    # Einwohner= Column(Integer)
    InzidenzFallNeu = Column(Float)

    # Einwohner_AG_A00_A04= Column(Integer)
    InzidenzFallNeu_AG_A00_A04 = Column(Float)
    # Einwohner_AG_A05_A14= Column(Integer)
    InzidenzFallNeu_AG_A05_A14 = Column(Float)
    # Einwohner_AG_A15_A34= Column(Integer)
    InzidenzFallNeu_AG_A15_A34 = Column(Float)
    # Einwohner_AG_A35_A59= Column(Integer)
    InzidenzFallNeu_AG_A35_A59 = Column(Float)
    # Einwohner_AG_A60_A79= Column(Integer)
    InzidenzFallNeu_AG_A60_A79 = Column(Float)
    # Einwohner_AG_A80Plus= Column(Integer)
    InzidenzFallNeu_AG_A80Plus = Column(Float)

    MeldeTag_AnzahlFallNeu_Gestern = Column(Integer)
    MeldeTag_AnzahlFall_Gestern = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_Gestern = Column(Integer)
    MeldeTag_AnzahlTodesfall_Gestern = Column(Integer)

    MeldeTag_AnzahlFallNeu_AG_A00_A04_Gestern = Column(Integer)
    MeldeTag_AnzahlFall_AG_A00_A04_Gestern = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A00_A04_Gestern = Column(Integer)
    MeldeTag_AnzahlTodesfall_AG_A00_A04_Gestern = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A05_A14_Gestern = Column(Integer)
    MeldeTag_AnzahlFall_AG_A05_A14_Gestern = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A05_A14_Gestern = Column(Integer)
    MeldeTag_AnzahlTodesfall_AG_A05_A14_Gestern = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A15_A34_Gestern = Column(Integer)
    MeldeTag_AnzahlFall_AG_A15_A34_Gestern = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A15_A34_Gestern = Column(Integer)
    MeldeTag_AnzahlTodesfall_AG_A15_A34_Gestern = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A35_A59_Gestern = Column(Integer)
    MeldeTag_AnzahlFall_AG_A35_A59_Gestern = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A35_A59_Gestern = Column(Integer)
    MeldeTag_AnzahlTodesfall_AG_A35_A59_Gestern = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A60_A79_Gestern = Column(Integer)
    MeldeTag_AnzahlFall_AG_A60_A79_Gestern = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A60_A79_Gestern = Column(Integer)
    MeldeTag_AnzahlTodesfall_AG_A60_A79_Gestern = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A80Plus_Gestern = Column(Integer)
    MeldeTag_AnzahlFall_AG_A80Plus_Gestern = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A80Plus_Gestern = Column(Integer)
    MeldeTag_AnzahlTodesfall_AG_A80Plus_Gestern = Column(Integer)

    MeldeTag_Vor7Tagen_AnzahlFallNeu_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFall_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfall_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A00_A04_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFall_AG_A00_A04_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A00_A04_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfall_AG_A00_A04_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A05_A14_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFall_AG_A05_A14_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A05_A14_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfall_AG_A05_A14_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A15_A34_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFall_AG_A15_A34_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A15_A34_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfall_AG_A15_A34_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A35_A59_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFall_AG_A35_A59_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A35_A59_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfall_AG_A35_A59_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A60_A79_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFall_AG_A60_A79_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A60_A79_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfall_AG_A60_A79_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A80Plus_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFall_AG_A80Plus_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A80Plus_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfall_AG_A80Plus_Vor8Tagen = Column(Integer)

    InzidenzTodesfallNeu = Column(Float)
    MeldeTag_InzidenzFall = Column(Float)
    MeldeTag_InzidenzTodesfall = Column(Float)
    MeldeTag_Fallsterblichkeit_Prozent = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzFall = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzTodesfall = Column(Float)
    MeldeTag_Vor7Tagen_Fallsterblichkeit_Prozent = Column(Float)
    InzidenzFall = Column(Float)
    InzidenzTodesfall = Column(Float)
    Fallsterblichkeit_Prozent = Column(Float)

    MeldeTag_InzidenzFall_AG_A00_A04 = Column(Float)
    MeldeTag_InzidenzTodesfall_AG_A00_A04 = Column(Float)
    MeldeTag_Fallsterblichkeit_Prozent_AG_A00_A04 = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzFall_AG_A00_A04 = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzTodesfall_AG_A00_A04 = Column(Float)
    MeldeTag_Vor7Tagen_Fallsterblichkeit_Prozent_AG_A00_A04 = Column(Float)
    InzidenzFall_AG_A00_A04 = Column(Float)
    InzidenzTodesfall_AG_A00_A04 = Column(Float)
    Fallsterblichkeit_Prozent_AG_A00_A04 = Column(Float)
    MeldeTag_InzidenzFall_AG_A05_A14 = Column(Float)
    MeldeTag_InzidenzTodesfall_AG_A05_A14 = Column(Float)
    MeldeTag_Fallsterblichkeit_Prozent_AG_A05_A14 = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzFall_AG_A05_A14 = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzTodesfall_AG_A05_A14 = Column(Float)
    MeldeTag_Vor7Tagen_Fallsterblichkeit_Prozent_AG_A05_A14 = Column(Float)
    InzidenzFall_AG_A05_A14 = Column(Float)
    InzidenzTodesfall_AG_A05_A14 = Column(Float)
    Fallsterblichkeit_Prozent_AG_A05_A14 = Column(Float)
    MeldeTag_InzidenzFall_AG_A15_A34 = Column(Float)
    MeldeTag_InzidenzTodesfall_AG_A15_A34 = Column(Float)
    MeldeTag_Fallsterblichkeit_Prozent_AG_A15_A34 = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzFall_AG_A15_A34 = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzTodesfall_AG_A15_A34 = Column(Float)
    MeldeTag_Vor7Tagen_Fallsterblichkeit_Prozent_AG_A15_A34 = Column(Float)
    InzidenzFall_AG_A15_A34 = Column(Float)
    InzidenzTodesfall_AG_A15_A34 = Column(Float)
    Fallsterblichkeit_Prozent_AG_A15_A34 = Column(Float)
    MeldeTag_InzidenzFall_AG_A35_A59 = Column(Float)
    MeldeTag_InzidenzTodesfall_AG_A35_A59 = Column(Float)
    MeldeTag_Fallsterblichkeit_Prozent_AG_A35_A59 = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzFall_AG_A35_A59 = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzTodesfall_AG_A35_A59 = Column(Float)
    MeldeTag_Vor7Tagen_Fallsterblichkeit_Prozent_AG_A35_A59 = Column(Float)
    InzidenzFall_AG_A35_A59 = Column(Float)
    InzidenzTodesfall_AG_A35_A59 = Column(Float)
    Fallsterblichkeit_Prozent_AG_A35_A59 = Column(Float)
    MeldeTag_InzidenzFall_AG_A60_A79 = Column(Float)
    MeldeTag_InzidenzTodesfall_AG_A60_A79 = Column(Float)
    MeldeTag_Fallsterblichkeit_Prozent_AG_A60_A79 = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzFall_AG_A60_A79 = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzTodesfall_AG_A60_A79 = Column(Float)
    MeldeTag_Vor7Tagen_Fallsterblichkeit_Prozent_AG_A60_A79 = Column(Float)
    InzidenzFall_AG_A60_A79 = Column(Float)
    InzidenzTodesfall_AG_A60_A79 = Column(Float)
    Fallsterblichkeit_Prozent_AG_A60_A79 = Column(Float)
    MeldeTag_InzidenzFall_AG_A80Plus = Column(Float)
    MeldeTag_InzidenzTodesfall_AG_A80Plus = Column(Float)
    MeldeTag_Fallsterblichkeit_Prozent_AG_A80Plus = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzFall_AG_A80Plus = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzTodesfall_AG_A80Plus = Column(Float)
    MeldeTag_Vor7Tagen_Fallsterblichkeit_Prozent_AG_A80Plus = Column(Float)
    InzidenzFall_AG_A80Plus = Column(Float)
    InzidenzTodesfall_AG_A80Plus = Column(Float)
    Fallsterblichkeit_Prozent_AG_A80Plus = Column(Float)

    MeldeTag_InzidenzFall_Gestern = Column(Float)
    MeldeTag_InzidenzTodesfall_Gestern = Column(Float)
    MeldeTag_Fallsterblichkeit_Prozent_Gestern = Column(Float)

    MeldeTag_InzidenzFall_AG_A00_A04_Gestern = Column(Float)
    MeldeTag_InzidenzTodesfall_AG_A00_A04_Gestern = Column(Float)
    MeldeTag_Fallsterblichkeit_Prozent_AG_A00_A04_Gestern = Column(Float)
    MeldeTag_InzidenzFall_AG_A05_A14_Gestern = Column(Float)
    MeldeTag_InzidenzTodesfall_AG_A05_A14_Gestern = Column(Float)
    MeldeTag_Fallsterblichkeit_Prozent_AG_A05_A14_Gestern = Column(Float)
    MeldeTag_InzidenzFall_AG_A15_A34_Gestern = Column(Float)
    MeldeTag_InzidenzTodesfall_AG_A15_A34_Gestern = Column(Float)
    MeldeTag_Fallsterblichkeit_Prozent_AG_A15_A34_Gestern = Column(Float)
    MeldeTag_InzidenzFall_AG_A35_A59_Gestern = Column(Float)
    MeldeTag_InzidenzTodesfall_AG_A35_A59_Gestern = Column(Float)
    MeldeTag_Fallsterblichkeit_Prozent_AG_A35_A59_Gestern = Column(Float)
    MeldeTag_InzidenzFall_AG_A60_A79_Gestern = Column(Float)
    MeldeTag_InzidenzTodesfall_AG_A60_A79_Gestern = Column(Float)
    MeldeTag_Fallsterblichkeit_Prozent_AG_A60_A79_Gestern = Column(Float)
    MeldeTag_InzidenzFall_AG_A80Plus_Gestern = Column(Float)
    MeldeTag_InzidenzTodesfall_AG_A80Plus_Gestern = Column(Float)
    MeldeTag_Fallsterblichkeit_Prozent_AG_A80Plus_Gestern = Column(Float)

    MeldeTag_Vor7Tagen_InzidenzFall_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzTodesfall_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_Fallsterblichkeit_Prozent_Vor8Tagen = Column(Float)

    MeldeTag_Vor7Tagen_InzidenzFall_AG_A00_A04_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzTodesfall_AG_A00_A04_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_Fallsterblichkeit_Prozent_AG_A00_A04_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzFall_AG_A05_A14_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzTodesfall_AG_A05_A14_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_Fallsterblichkeit_Prozent_AG_A05_A14_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzFall_AG_A15_A34_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzTodesfall_AG_A15_A34_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_Fallsterblichkeit_Prozent_AG_A15_A34_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzFall_AG_A35_A59_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzTodesfall_AG_A35_A59_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_Fallsterblichkeit_Prozent_AG_A35_A59_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzFall_AG_A60_A79_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzTodesfall_AG_A60_A79_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_Fallsterblichkeit_Prozent_AG_A60_A79_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzFall_AG_A80Plus_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzTodesfall_AG_A80Plus_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_Fallsterblichkeit_Prozent_AG_A80Plus_Vor8Tagen = Column(Float)

    MeldeTag_AnzahlFallNeu_7TageSumme = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_7TageSumme = Column(Integer)
    AnzahlFallNeu_7TageSumme = Column(Integer)
    AnzahlFallNeu_7TageSumme_Trend = Column(Float)
    AnzahlFallNeu_7TageSumme_7_Tage_davor = Column(Integer)
    AnzahlTodesfallNeu_7TageSumme = Column(Integer)
    AnzahlTodesfallNeu_7TageSumme_Trend = Column(Float)
    AnzahlTodesfallNeu_7TageSumme_7_Tage_davor = Column(Integer)
    AnzahlGenesenNeu_7TageSumme = Column(Integer)
    AnzahlGenesenNeu_7TageSumme_Trend = Column(Float)

    MeldeTag_AnzahlFallNeu_AG_A00_A04_7TageSumme = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A00_A04_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A00_A04_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A00_A04_7TageSumme = Column(Integer)
    AnzahlFallNeu_AG_A00_A04_7TageSumme = Column(Integer)
    AnzahlFallNeu_AG_A00_A04_7TageSumme_Trend = Column(Float)
    AnzahlTodesfallNeu_AG_A00_A04_7TageSumme = Column(Integer)
    AnzahlTodesfallNeu_AG_A00_A04_7TageSumme_Trend = Column(Float)
    MeldeTag_AnzahlFallNeu_AG_A05_A14_7TageSumme = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A05_A14_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A05_A14_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A05_A14_7TageSumme = Column(Integer)
    AnzahlFallNeu_AG_A05_A14_7TageSumme = Column(Integer)
    AnzahlFallNeu_AG_A05_A14_7TageSumme_Trend = Column(Float)
    AnzahlTodesfallNeu_AG_A05_A14_7TageSumme = Column(Integer)
    AnzahlTodesfallNeu_AG_A05_A14_7TageSumme_Trend = Column(Float)
    MeldeTag_AnzahlFallNeu_AG_A15_A34_7TageSumme = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A15_A34_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A15_A34_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A15_A34_7TageSumme = Column(Integer)
    AnzahlFallNeu_AG_A15_A34_7TageSumme = Column(Integer)
    AnzahlFallNeu_AG_A15_A34_7TageSumme_Trend = Column(Float)
    AnzahlTodesfallNeu_AG_A15_A34_7TageSumme = Column(Integer)
    AnzahlTodesfallNeu_AG_A15_A34_7TageSumme_Trend = Column(Float)
    MeldeTag_AnzahlFallNeu_AG_A35_A59_7TageSumme = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A35_A59_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A35_A59_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A35_A59_7TageSumme = Column(Integer)
    AnzahlFallNeu_AG_A35_A59_7TageSumme = Column(Integer)
    AnzahlFallNeu_AG_A35_A59_7TageSumme_Trend = Column(Float)
    AnzahlTodesfallNeu_AG_A35_A59_7TageSumme = Column(Integer)
    AnzahlTodesfallNeu_AG_A35_A59_7TageSumme_Trend = Column(Float)
    MeldeTag_AnzahlFallNeu_AG_A60_A79_7TageSumme = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A60_A79_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A60_A79_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A60_A79_7TageSumme = Column(Integer)
    AnzahlFallNeu_AG_A60_A79_7TageSumme = Column(Integer)
    AnzahlFallNeu_AG_A60_A79_7TageSumme_Trend = Column(Float)
    AnzahlTodesfallNeu_AG_A60_A79_7TageSumme = Column(Integer)
    AnzahlTodesfallNeu_AG_A60_A79_7TageSumme_Trend = Column(Float)
    MeldeTag_AnzahlFallNeu_AG_A80Plus_7TageSumme = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A80Plus_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A80Plus_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A80Plus_7TageSumme = Column(Integer)
    AnzahlFallNeu_AG_A80Plus_7TageSumme = Column(Integer)
    AnzahlFallNeu_AG_A80Plus_7TageSumme_Trend = Column(Float)
    AnzahlTodesfallNeu_AG_A80Plus_7TageSumme = Column(Integer)
    AnzahlTodesfallNeu_AG_A80Plus_7TageSumme_Trend = Column(Float)

    InzidenzFallNeu_7TageSumme = Column(Float)
    InzidenzFallNeu_7TageSumme_Trend = Column(Float)
    InzidenzFallNeu_7TageSumme_7_Tage_davor = Column(Float)
    InzidenzFallNeu_7TageSumme_Trend_Spezial = Column(Float)
    InzidenzFallNeu_7TageSumme_R = Column(Float)
    InzidenzFallNeu_Prognose_1_Wochen = Column(Float)
    InzidenzFallNeu_Prognose_2_Wochen = Column(Float)
    InzidenzFallNeu_Prognose_4_Wochen = Column(Float)
    InzidenzFallNeu_Prognose_8_Wochen = Column(Float)
    InzidenzFallNeu_Tage_bis_50 = Column(Float)
    InzidenzFallNeu_Tage_bis_100 = Column(Float)
    Kontaktrisiko = Column(Float)

    InzidenzFallNeu_AG_A00_A04_7TageSumme = Column(Float)
    InzidenzFallNeu_AG_A00_A04_7TageSumme_Trend = Column(Float)
    InzidenzFallNeu_AG_A05_A14_7TageSumme = Column(Float)
    InzidenzFallNeu_AG_A05_A14_7TageSumme_Trend = Column(Float)
    InzidenzFallNeu_AG_A15_A34_7TageSumme = Column(Float)
    InzidenzFallNeu_AG_A15_A34_7TageSumme_Trend = Column(Float)
    InzidenzFallNeu_AG_A35_A59_7TageSumme = Column(Float)
    InzidenzFallNeu_AG_A35_A59_7TageSumme_Trend = Column(Float)
    InzidenzFallNeu_AG_A60_A79_7TageSumme = Column(Float)
    InzidenzFallNeu_AG_A60_A79_7TageSumme_Trend = Column(Float)
    InzidenzFallNeu_AG_A80Plus_7TageSumme = Column(Float)
    InzidenzFallNeu_AG_A80Plus_7TageSumme_Trend = Column(Float)

    MeldeTag_AnzahlFallNeu_Gestern_7TageSumme = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_Gestern_7TageSumme = Column(Integer)

    MeldeTag_AnzahlFallNeu_AG_A00_A04_Gestern_7TageSumme = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A00_A04_Gestern_7TageSumme = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A05_A14_Gestern_7TageSumme = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A05_A14_Gestern_7TageSumme = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A15_A34_Gestern_7TageSumme = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A15_A34_Gestern_7TageSumme = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A35_A59_Gestern_7TageSumme = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A35_A59_Gestern_7TageSumme = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A60_A79_Gestern_7TageSumme = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A60_A79_Gestern_7TageSumme = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A80Plus_Gestern_7TageSumme = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A80Plus_Gestern_7TageSumme = Column(Integer)

    MeldeTag_Vor7Tagen_AnzahlFallNeu_Vor8Tagen_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_Vor8Tagen_7TageSumme = Column(Integer)

    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A00_A04_Vor8Tagen_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A00_A04_Vor8Tagen_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A05_A14_Vor8Tagen_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A05_A14_Vor8Tagen_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A15_A34_Vor8Tagen_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A15_A34_Vor8Tagen_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A35_A59_Vor8Tagen_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A35_A59_Vor8Tagen_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A60_A79_Vor8Tagen_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A60_A79_Vor8Tagen_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A80Plus_Vor8Tagen_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A80Plus_Vor8Tagen_7TageSumme = Column(Integer)
    InzidenzTodesfallNeu_7TageSumme = Column(Float)
    InzidenzTodesfallNeu_7TageSumme_Trend = Column(Float)
    InzidenzTodesfallNeu_7TageSumme_7_Tage_davor = Column(Float)
    InzidenzTodesfallNeu_7TageSumme_Trend_Spezial = Column(Float)
    DatenstandTag_Diff = Column(Integer)
    MeldeTag_InzidenzFallNeu_Gestern_7TageSumme = Column(Float)
    AnzahlFallNeu_7TageSumme_Dropped = Column(Integer)
    ProzentFallNeu_7TageSumme_Dropped = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzFallNeu_Vor8Tagen_7TageSumme = Column(Float)
    MeldeTag_InzidenzFallNeu_Trend = Column(Float)
    MeldeTag_InzidenzFallNeu_R = Column(Float)
    MeldeTag_InzidenzFallNeu_Prognose_4_Wochen = Column(Float)
    PublikationsdauerFallNeu_Min_Neg = Column(Integer)

    # up
    Bundesrepublik_ID = Column(Integer, ForeignKey("bundesrepublik.ID"))
    Bundesrepublik = relationship(
        "Bundesrepublik", back_populates="Daten", lazy="joined"
    )


class Bundesland(Base):
    __tablename__ = "bundeslaender"
    ID = Column(Integer, primary_key=True, index=True)

    Name = Column(String, nullable=False)
    Kuerzel = Column(String, nullable=False)
    Flaeche = Column(Float)
    # Dichte = Column(Float)
    Einwohner = Column(Integer)
    Einwohner_AG_A00_A04 = Column(Integer)
    Einwohner_AG_A05_A14 = Column(Integer)
    Einwohner_AG_A15_A34 = Column(Integer)
    Einwohner_AG_A35_A59 = Column(Integer)
    Einwohner_AG_A60_A79 = Column(Integer)
    Einwohner_AG_A80Plus = Column(Integer)

    # up

    BR_ID = Column(Integer, ForeignKey("bundesrepublik.ID"))
    Bundesrepublik = relationship("Bundesrepublik", back_populates="Bundeslaender")

    # down
    Landkreise = relationship("Landkreis", back_populates="Bundesland")
    Daten = relationship(
        "Bundesland_Daten", back_populates="Bundesland"
    )

    # alle_faelle = relationship("Fall_Daten_Taeglich", back_populates="bundesland")


class Bundesland_Daten(Base):
    __tablename__ = "bundeslaender_daten"
    # __table_args__ = (UniqueConstraint("ID", "MeldeDatum"),)
    ID = Column(Integer, primary_key=True, index=True)

    DatenstandTag = Column(Integer)
    Datum = Column(Date, index=True)
    MeldeTag_AnzahlFallNeu = Column(Integer)
    MeldeTag_AnzahlFall = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu = Column(Integer)
    MeldeTag_AnzahlTodesfall = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFall = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfall = Column(Integer)
    AnzahlFall = Column(Integer)
    AnzahlFallNeu = Column(Integer)
    AnzahlTodesfall = Column(Integer)
    AnzahlTodesfallNeu = Column(Integer)
    AnzahlGenesen = Column(Integer)
    AnzahlGenesenNeu = Column(Integer)
    PublikationsdauerFallNeu_Min = Column(Integer)
    PublikationsdauerFallNeu_Max = Column(Integer)
    PublikationsdauerFallNeu_Schnitt = Column(Float)
    PublikationsdauerFallNeu_Median = Column(Float)
    PublikationsdauerFallNeu_StdAbw = Column(Float)
    PublikationsdauerFallNeu_Fallbasis = Column(Integer)
    DatenstandTag_Max = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A00_A04 = Column(Integer)
    MeldeTag_AnzahlFall_AG_A00_A04 = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A00_A04 = Column(Integer)
    MeldeTag_AnzahlTodesfall_AG_A00_A04 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A00_A04 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFall_AG_A00_A04 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A00_A04 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfall_AG_A00_A04 = Column(Integer)
    AnzahlFall_AG_A00_A04 = Column(Integer)
    AnzahlFallNeu_AG_A00_A04 = Column(Integer)
    AnzahlTodesfall_AG_A00_A04 = Column(Integer)
    AnzahlTodesfallNeu_AG_A00_A04 = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A05_A14 = Column(Integer)
    MeldeTag_AnzahlFall_AG_A05_A14 = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A05_A14 = Column(Integer)
    MeldeTag_AnzahlTodesfall_AG_A05_A14 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A05_A14 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFall_AG_A05_A14 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A05_A14 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfall_AG_A05_A14 = Column(Integer)
    AnzahlFall_AG_A05_A14 = Column(Integer)
    AnzahlFallNeu_AG_A05_A14 = Column(Integer)
    AnzahlTodesfall_AG_A05_A14 = Column(Integer)
    AnzahlTodesfallNeu_AG_A05_A14 = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A15_A34 = Column(Integer)
    MeldeTag_AnzahlFall_AG_A15_A34 = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A15_A34 = Column(Integer)
    MeldeTag_AnzahlTodesfall_AG_A15_A34 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A15_A34 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFall_AG_A15_A34 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A15_A34 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfall_AG_A15_A34 = Column(Integer)
    AnzahlFall_AG_A15_A34 = Column(Integer)
    AnzahlFallNeu_AG_A15_A34 = Column(Integer)
    AnzahlTodesfall_AG_A15_A34 = Column(Integer)
    AnzahlTodesfallNeu_AG_A15_A34 = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A35_A59 = Column(Integer)
    MeldeTag_AnzahlFall_AG_A35_A59 = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A35_A59 = Column(Integer)
    MeldeTag_AnzahlTodesfall_AG_A35_A59 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A35_A59 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFall_AG_A35_A59 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A35_A59 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfall_AG_A35_A59 = Column(Integer)
    AnzahlFall_AG_A35_A59 = Column(Integer)
    AnzahlFallNeu_AG_A35_A59 = Column(Integer)
    AnzahlTodesfall_AG_A35_A59 = Column(Integer)
    AnzahlTodesfallNeu_AG_A35_A59 = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A60_A79 = Column(Integer)
    MeldeTag_AnzahlFall_AG_A60_A79 = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A60_A79 = Column(Integer)
    MeldeTag_AnzahlTodesfall_AG_A60_A79 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A60_A79 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFall_AG_A60_A79 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A60_A79 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfall_AG_A60_A79 = Column(Integer)
    AnzahlFall_AG_A60_A79 = Column(Integer)
    AnzahlFallNeu_AG_A60_A79 = Column(Integer)
    AnzahlTodesfall_AG_A60_A79 = Column(Integer)
    AnzahlTodesfallNeu_AG_A60_A79 = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A80Plus = Column(Integer)
    MeldeTag_AnzahlFall_AG_A80Plus = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A80Plus = Column(Integer)
    MeldeTag_AnzahlTodesfall_AG_A80Plus = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A80Plus = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFall_AG_A80Plus = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A80Plus = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfall_AG_A80Plus = Column(Integer)

    AnzahlFall_AG_A80Plus = Column(Integer)
    AnzahlFallNeu_AG_A80Plus = Column(Integer)
    AnzahlTodesfall_AG_A80Plus = Column(Integer)
    AnzahlTodesfallNeu_AG_A80Plus = Column(Integer)
    # Einwohner= Column(Integer)
    InzidenzFallNeu = Column(Float)

    # Einwohner_AG_A00_A04= Column(Integer)
    InzidenzFallNeu_AG_A00_A04 = Column(Float)
    # Einwohner_AG_A05_A14= Column(Integer)
    InzidenzFallNeu_AG_A05_A14 = Column(Float)
    # Einwohner_AG_A15_A34= Column(Integer)
    InzidenzFallNeu_AG_A15_A34 = Column(Float)
    # Einwohner_AG_A35_A59= Column(Integer)
    InzidenzFallNeu_AG_A35_A59 = Column(Float)
    # Einwohner_AG_A60_A79= Column(Integer)
    InzidenzFallNeu_AG_A60_A79 = Column(Float)
    # Einwohner_AG_A80Plus= Column(Integer)
    InzidenzFallNeu_AG_A80Plus = Column(Float)

    MeldeTag_AnzahlFallNeu_Gestern = Column(Integer)
    MeldeTag_AnzahlFall_Gestern = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_Gestern = Column(Integer)
    MeldeTag_AnzahlTodesfall_Gestern = Column(Integer)

    MeldeTag_AnzahlFallNeu_AG_A00_A04_Gestern = Column(Integer)
    MeldeTag_AnzahlFall_AG_A00_A04_Gestern = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A00_A04_Gestern = Column(Integer)
    MeldeTag_AnzahlTodesfall_AG_A00_A04_Gestern = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A05_A14_Gestern = Column(Integer)
    MeldeTag_AnzahlFall_AG_A05_A14_Gestern = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A05_A14_Gestern = Column(Integer)
    MeldeTag_AnzahlTodesfall_AG_A05_A14_Gestern = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A15_A34_Gestern = Column(Integer)
    MeldeTag_AnzahlFall_AG_A15_A34_Gestern = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A15_A34_Gestern = Column(Integer)
    MeldeTag_AnzahlTodesfall_AG_A15_A34_Gestern = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A35_A59_Gestern = Column(Integer)
    MeldeTag_AnzahlFall_AG_A35_A59_Gestern = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A35_A59_Gestern = Column(Integer)
    MeldeTag_AnzahlTodesfall_AG_A35_A59_Gestern = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A60_A79_Gestern = Column(Integer)
    MeldeTag_AnzahlFall_AG_A60_A79_Gestern = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A60_A79_Gestern = Column(Integer)
    MeldeTag_AnzahlTodesfall_AG_A60_A79_Gestern = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A80Plus_Gestern = Column(Integer)
    MeldeTag_AnzahlFall_AG_A80Plus_Gestern = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A80Plus_Gestern = Column(Integer)
    MeldeTag_AnzahlTodesfall_AG_A80Plus_Gestern = Column(Integer)

    MeldeTag_Vor7Tagen_AnzahlFallNeu_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFall_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfall_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A00_A04_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFall_AG_A00_A04_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A00_A04_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfall_AG_A00_A04_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A05_A14_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFall_AG_A05_A14_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A05_A14_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfall_AG_A05_A14_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A15_A34_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFall_AG_A15_A34_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A15_A34_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfall_AG_A15_A34_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A35_A59_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFall_AG_A35_A59_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A35_A59_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfall_AG_A35_A59_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A60_A79_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFall_AG_A60_A79_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A60_A79_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfall_AG_A60_A79_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A80Plus_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFall_AG_A80Plus_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A80Plus_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfall_AG_A80Plus_Vor8Tagen = Column(Integer)

    InzidenzTodesfallNeu = Column(Float)
    MeldeTag_InzidenzFall = Column(Float)
    MeldeTag_InzidenzTodesfall = Column(Float)
    MeldeTag_Fallsterblichkeit_Prozent = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzFall = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzTodesfall = Column(Float)
    MeldeTag_Vor7Tagen_Fallsterblichkeit_Prozent = Column(Float)
    InzidenzFall = Column(Float)
    InzidenzTodesfall = Column(Float)
    Fallsterblichkeit_Prozent = Column(Float)

    MeldeTag_InzidenzFall_AG_A00_A04 = Column(Float)
    MeldeTag_InzidenzTodesfall_AG_A00_A04 = Column(Float)
    MeldeTag_Fallsterblichkeit_Prozent_AG_A00_A04 = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzFall_AG_A00_A04 = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzTodesfall_AG_A00_A04 = Column(Float)
    MeldeTag_Vor7Tagen_Fallsterblichkeit_Prozent_AG_A00_A04 = Column(Float)
    InzidenzFall_AG_A00_A04 = Column(Float)
    InzidenzTodesfall_AG_A00_A04 = Column(Float)
    Fallsterblichkeit_Prozent_AG_A00_A04 = Column(Float)
    MeldeTag_InzidenzFall_AG_A05_A14 = Column(Float)
    MeldeTag_InzidenzTodesfall_AG_A05_A14 = Column(Float)
    MeldeTag_Fallsterblichkeit_Prozent_AG_A05_A14 = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzFall_AG_A05_A14 = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzTodesfall_AG_A05_A14 = Column(Float)
    MeldeTag_Vor7Tagen_Fallsterblichkeit_Prozent_AG_A05_A14 = Column(Float)
    InzidenzFall_AG_A05_A14 = Column(Float)
    InzidenzTodesfall_AG_A05_A14 = Column(Float)
    Fallsterblichkeit_Prozent_AG_A05_A14 = Column(Float)
    MeldeTag_InzidenzFall_AG_A15_A34 = Column(Float)
    MeldeTag_InzidenzTodesfall_AG_A15_A34 = Column(Float)
    MeldeTag_Fallsterblichkeit_Prozent_AG_A15_A34 = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzFall_AG_A15_A34 = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzTodesfall_AG_A15_A34 = Column(Float)
    MeldeTag_Vor7Tagen_Fallsterblichkeit_Prozent_AG_A15_A34 = Column(Float)
    InzidenzFall_AG_A15_A34 = Column(Float)
    InzidenzTodesfall_AG_A15_A34 = Column(Float)
    Fallsterblichkeit_Prozent_AG_A15_A34 = Column(Float)
    MeldeTag_InzidenzFall_AG_A35_A59 = Column(Float)
    MeldeTag_InzidenzTodesfall_AG_A35_A59 = Column(Float)
    MeldeTag_Fallsterblichkeit_Prozent_AG_A35_A59 = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzFall_AG_A35_A59 = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzTodesfall_AG_A35_A59 = Column(Float)
    MeldeTag_Vor7Tagen_Fallsterblichkeit_Prozent_AG_A35_A59 = Column(Float)
    InzidenzFall_AG_A35_A59 = Column(Float)
    InzidenzTodesfall_AG_A35_A59 = Column(Float)
    Fallsterblichkeit_Prozent_AG_A35_A59 = Column(Float)
    MeldeTag_InzidenzFall_AG_A60_A79 = Column(Float)
    MeldeTag_InzidenzTodesfall_AG_A60_A79 = Column(Float)
    MeldeTag_Fallsterblichkeit_Prozent_AG_A60_A79 = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzFall_AG_A60_A79 = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzTodesfall_AG_A60_A79 = Column(Float)
    MeldeTag_Vor7Tagen_Fallsterblichkeit_Prozent_AG_A60_A79 = Column(Float)
    InzidenzFall_AG_A60_A79 = Column(Float)
    InzidenzTodesfall_AG_A60_A79 = Column(Float)
    Fallsterblichkeit_Prozent_AG_A60_A79 = Column(Float)
    MeldeTag_InzidenzFall_AG_A80Plus = Column(Float)
    MeldeTag_InzidenzTodesfall_AG_A80Plus = Column(Float)
    MeldeTag_Fallsterblichkeit_Prozent_AG_A80Plus = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzFall_AG_A80Plus = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzTodesfall_AG_A80Plus = Column(Float)
    MeldeTag_Vor7Tagen_Fallsterblichkeit_Prozent_AG_A80Plus = Column(Float)
    InzidenzFall_AG_A80Plus = Column(Float)
    InzidenzTodesfall_AG_A80Plus = Column(Float)
    Fallsterblichkeit_Prozent_AG_A80Plus = Column(Float)

    MeldeTag_InzidenzFall_Gestern = Column(Float)
    MeldeTag_InzidenzTodesfall_Gestern = Column(Float)
    MeldeTag_Fallsterblichkeit_Prozent_Gestern = Column(Float)

    MeldeTag_InzidenzFall_AG_A00_A04_Gestern = Column(Float)
    MeldeTag_InzidenzTodesfall_AG_A00_A04_Gestern = Column(Float)
    MeldeTag_Fallsterblichkeit_Prozent_AG_A00_A04_Gestern = Column(Float)
    MeldeTag_InzidenzFall_AG_A05_A14_Gestern = Column(Float)
    MeldeTag_InzidenzTodesfall_AG_A05_A14_Gestern = Column(Float)
    MeldeTag_Fallsterblichkeit_Prozent_AG_A05_A14_Gestern = Column(Float)
    MeldeTag_InzidenzFall_AG_A15_A34_Gestern = Column(Float)
    MeldeTag_InzidenzTodesfall_AG_A15_A34_Gestern = Column(Float)
    MeldeTag_Fallsterblichkeit_Prozent_AG_A15_A34_Gestern = Column(Float)
    MeldeTag_InzidenzFall_AG_A35_A59_Gestern = Column(Float)
    MeldeTag_InzidenzTodesfall_AG_A35_A59_Gestern = Column(Float)
    MeldeTag_Fallsterblichkeit_Prozent_AG_A35_A59_Gestern = Column(Float)
    MeldeTag_InzidenzFall_AG_A60_A79_Gestern = Column(Float)
    MeldeTag_InzidenzTodesfall_AG_A60_A79_Gestern = Column(Float)
    MeldeTag_Fallsterblichkeit_Prozent_AG_A60_A79_Gestern = Column(Float)
    MeldeTag_InzidenzFall_AG_A80Plus_Gestern = Column(Float)
    MeldeTag_InzidenzTodesfall_AG_A80Plus_Gestern = Column(Float)
    MeldeTag_Fallsterblichkeit_Prozent_AG_A80Plus_Gestern = Column(Float)

    MeldeTag_Vor7Tagen_InzidenzFall_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzTodesfall_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_Fallsterblichkeit_Prozent_Vor8Tagen = Column(Float)

    MeldeTag_Vor7Tagen_InzidenzFall_AG_A00_A04_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzTodesfall_AG_A00_A04_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_Fallsterblichkeit_Prozent_AG_A00_A04_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzFall_AG_A05_A14_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzTodesfall_AG_A05_A14_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_Fallsterblichkeit_Prozent_AG_A05_A14_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzFall_AG_A15_A34_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzTodesfall_AG_A15_A34_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_Fallsterblichkeit_Prozent_AG_A15_A34_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzFall_AG_A35_A59_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzTodesfall_AG_A35_A59_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_Fallsterblichkeit_Prozent_AG_A35_A59_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzFall_AG_A60_A79_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzTodesfall_AG_A60_A79_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_Fallsterblichkeit_Prozent_AG_A60_A79_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzFall_AG_A80Plus_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzTodesfall_AG_A80Plus_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_Fallsterblichkeit_Prozent_AG_A80Plus_Vor8Tagen = Column(Float)

    MeldeTag_AnzahlFallNeu_7TageSumme = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_7TageSumme = Column(Integer)
    AnzahlFallNeu_7TageSumme = Column(Integer)
    AnzahlFallNeu_7TageSumme_Trend = Column(Float)
    AnzahlFallNeu_7TageSumme_7_Tage_davor = Column(Integer)
    AnzahlTodesfallNeu_7TageSumme = Column(Integer)
    AnzahlTodesfallNeu_7TageSumme_Trend = Column(Float)
    AnzahlTodesfallNeu_7TageSumme_7_Tage_davor = Column(Integer)
    AnzahlGenesenNeu_7TageSumme = Column(Integer)
    AnzahlGenesenNeu_7TageSumme_Trend = Column(Float)

    MeldeTag_AnzahlFallNeu_AG_A00_A04_7TageSumme = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A00_A04_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A00_A04_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A00_A04_7TageSumme = Column(Integer)
    AnzahlFallNeu_AG_A00_A04_7TageSumme = Column(Integer)
    AnzahlFallNeu_AG_A00_A04_7TageSumme_Trend = Column(Float)
    AnzahlTodesfallNeu_AG_A00_A04_7TageSumme = Column(Integer)
    AnzahlTodesfallNeu_AG_A00_A04_7TageSumme_Trend = Column(Float)
    MeldeTag_AnzahlFallNeu_AG_A05_A14_7TageSumme = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A05_A14_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A05_A14_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A05_A14_7TageSumme = Column(Integer)
    AnzahlFallNeu_AG_A05_A14_7TageSumme = Column(Integer)
    AnzahlFallNeu_AG_A05_A14_7TageSumme_Trend = Column(Float)
    AnzahlTodesfallNeu_AG_A05_A14_7TageSumme = Column(Integer)
    AnzahlTodesfallNeu_AG_A05_A14_7TageSumme_Trend = Column(Float)
    MeldeTag_AnzahlFallNeu_AG_A15_A34_7TageSumme = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A15_A34_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A15_A34_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A15_A34_7TageSumme = Column(Integer)
    AnzahlFallNeu_AG_A15_A34_7TageSumme = Column(Integer)
    AnzahlFallNeu_AG_A15_A34_7TageSumme_Trend = Column(Float)
    AnzahlTodesfallNeu_AG_A15_A34_7TageSumme = Column(Integer)
    AnzahlTodesfallNeu_AG_A15_A34_7TageSumme_Trend = Column(Float)
    MeldeTag_AnzahlFallNeu_AG_A35_A59_7TageSumme = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A35_A59_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A35_A59_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A35_A59_7TageSumme = Column(Integer)
    AnzahlFallNeu_AG_A35_A59_7TageSumme = Column(Integer)
    AnzahlFallNeu_AG_A35_A59_7TageSumme_Trend = Column(Float)
    AnzahlTodesfallNeu_AG_A35_A59_7TageSumme = Column(Integer)
    AnzahlTodesfallNeu_AG_A35_A59_7TageSumme_Trend = Column(Float)
    MeldeTag_AnzahlFallNeu_AG_A60_A79_7TageSumme = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A60_A79_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A60_A79_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A60_A79_7TageSumme = Column(Integer)
    AnzahlFallNeu_AG_A60_A79_7TageSumme = Column(Integer)
    AnzahlFallNeu_AG_A60_A79_7TageSumme_Trend = Column(Float)
    AnzahlTodesfallNeu_AG_A60_A79_7TageSumme = Column(Integer)
    AnzahlTodesfallNeu_AG_A60_A79_7TageSumme_Trend = Column(Float)
    MeldeTag_AnzahlFallNeu_AG_A80Plus_7TageSumme = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A80Plus_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A80Plus_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A80Plus_7TageSumme = Column(Integer)
    AnzahlFallNeu_AG_A80Plus_7TageSumme = Column(Integer)
    AnzahlFallNeu_AG_A80Plus_7TageSumme_Trend = Column(Float)
    AnzahlTodesfallNeu_AG_A80Plus_7TageSumme = Column(Integer)
    AnzahlTodesfallNeu_AG_A80Plus_7TageSumme_Trend = Column(Float)

    InzidenzFallNeu_7TageSumme = Column(Float)
    InzidenzFallNeu_7TageSumme_Trend = Column(Float)
    InzidenzFallNeu_7TageSumme_7_Tage_davor = Column(Float)
    InzidenzFallNeu_7TageSumme_Trend_Spezial = Column(Float)
    InzidenzFallNeu_7TageSumme_R = Column(Float)
    InzidenzFallNeu_Prognose_1_Wochen = Column(Float)
    InzidenzFallNeu_Prognose_2_Wochen = Column(Float)
    InzidenzFallNeu_Prognose_4_Wochen = Column(Float)
    InzidenzFallNeu_Prognose_8_Wochen = Column(Float)
    InzidenzFallNeu_Tage_bis_50 = Column(Float)
    InzidenzFallNeu_Tage_bis_100 = Column(Float)
    Kontaktrisiko = Column(Float)

    InzidenzFallNeu_AG_A00_A04_7TageSumme = Column(Float)
    InzidenzFallNeu_AG_A00_A04_7TageSumme_Trend = Column(Float)
    InzidenzFallNeu_AG_A05_A14_7TageSumme = Column(Float)
    InzidenzFallNeu_AG_A05_A14_7TageSumme_Trend = Column(Float)
    InzidenzFallNeu_AG_A15_A34_7TageSumme = Column(Float)
    InzidenzFallNeu_AG_A15_A34_7TageSumme_Trend = Column(Float)
    InzidenzFallNeu_AG_A35_A59_7TageSumme = Column(Float)
    InzidenzFallNeu_AG_A35_A59_7TageSumme_Trend = Column(Float)
    InzidenzFallNeu_AG_A60_A79_7TageSumme = Column(Float)
    InzidenzFallNeu_AG_A60_A79_7TageSumme_Trend = Column(Float)
    InzidenzFallNeu_AG_A80Plus_7TageSumme = Column(Float)
    InzidenzFallNeu_AG_A80Plus_7TageSumme_Trend = Column(Float)

    MeldeTag_AnzahlFallNeu_Gestern_7TageSumme = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_Gestern_7TageSumme = Column(Integer)

    MeldeTag_AnzahlFallNeu_AG_A00_A04_Gestern_7TageSumme = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A00_A04_Gestern_7TageSumme = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A05_A14_Gestern_7TageSumme = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A05_A14_Gestern_7TageSumme = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A15_A34_Gestern_7TageSumme = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A15_A34_Gestern_7TageSumme = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A35_A59_Gestern_7TageSumme = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A35_A59_Gestern_7TageSumme = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A60_A79_Gestern_7TageSumme = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A60_A79_Gestern_7TageSumme = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A80Plus_Gestern_7TageSumme = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A80Plus_Gestern_7TageSumme = Column(Integer)

    MeldeTag_Vor7Tagen_AnzahlFallNeu_Vor8Tagen_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_Vor8Tagen_7TageSumme = Column(Integer)

    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A00_A04_Vor8Tagen_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A00_A04_Vor8Tagen_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A05_A14_Vor8Tagen_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A05_A14_Vor8Tagen_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A15_A34_Vor8Tagen_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A15_A34_Vor8Tagen_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A35_A59_Vor8Tagen_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A35_A59_Vor8Tagen_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A60_A79_Vor8Tagen_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A60_A79_Vor8Tagen_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A80Plus_Vor8Tagen_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A80Plus_Vor8Tagen_7TageSumme = Column(Integer)
    InzidenzTodesfallNeu_7TageSumme = Column(Float)
    InzidenzTodesfallNeu_7TageSumme_Trend = Column(Float)
    InzidenzTodesfallNeu_7TageSumme_7_Tage_davor = Column(Float)
    InzidenzTodesfallNeu_7TageSumme_Trend_Spezial = Column(Float)
    DatenstandTag_Diff = Column(Integer)
    MeldeTag_InzidenzFallNeu_Gestern_7TageSumme = Column(Float)
    AnzahlFallNeu_7TageSumme_Dropped = Column(Integer)
    ProzentFallNeu_7TageSumme_Dropped = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzFallNeu_Vor8Tagen_7TageSumme = Column(Float)
    MeldeTag_InzidenzFallNeu_Trend = Column(Float)
    MeldeTag_InzidenzFallNeu_R = Column(Float)
    MeldeTag_InzidenzFallNeu_Prognose_4_Wochen = Column(Float)
    PublikationsdauerFallNeu_Min_Neg = Column(Integer)

    # up
    Bundesland_ID = Column(Integer, ForeignKey("bundeslaender.ID"))
    Bundesland = relationship(
        "Bundesland", back_populates="Daten", lazy="joined"
    )
    """
    Altersgruppe_id = Column(Integer, ForeignKey("altersgruppen.ID"))
    Altersgruppe = relationship("Altersgruppe", back_populates="Bundesland_faelle")
    """
    # down

    # Zugehoerige_faelle = relationship("Fall_Daten_Taeglich", back_populates="bundesland_meldedatum")


class Landkreis(Base):
    __tablename__ = "landkreise"
    # __table_args__ = (UniqueConstraint("name", "typ", name="_lk_name_typ_uc"),)
    ID = Column(Integer, primary_key=True, index=True)

    Name = Column(String, nullable=False, index=True)
    Typ = Column(String, nullable=False)
    Flaeche = Column(Float)
    # Dichte = Column(Float)
    Einwohner = Column(Integer)
    Einwohner_AG_A00_A04 = Column(Integer)
    Einwohner_AG_A05_A14 = Column(Integer)
    Einwohner_AG_A15_A34 = Column(Integer)
    Einwohner_AG_A35_A59 = Column(Integer)
    Einwohner_AG_A60_A79 = Column(Integer)
    Einwohner_AG_A80Plus = Column(Integer)

    # up
    BL_ID = Column(Integer, ForeignKey("bundeslaender.ID"))
    Bundesland = relationship("Bundesland", back_populates="Landkreise")

    # down

    Daten = relationship(
        "Landkreis_Daten", back_populates="Landkreis"
    )

    # alle_faelle = relationship("Fall_Daten_Taeglich", back_populates="landkreis")


class Landkreis_Daten(Base):
    __tablename__ = "landkreise_daten"
    ID = Column(Integer, primary_key=True, index=True)

    DatenstandTag = Column(Integer)
    Datum = Column(Date, index=True)
    MeldeTag_AnzahlFallNeu = Column(Integer)
    MeldeTag_AnzahlFall = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu = Column(Integer)
    MeldeTag_AnzahlTodesfall = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFall = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfall = Column(Integer)
    AnzahlFall = Column(Integer)
    AnzahlFallNeu = Column(Integer)
    AnzahlTodesfall = Column(Integer)
    AnzahlTodesfallNeu = Column(Integer)
    AnzahlGenesen = Column(Integer)
    AnzahlGenesenNeu = Column(Integer)
    PublikationsdauerFallNeu_Min = Column(Integer)
    PublikationsdauerFallNeu_Max = Column(Integer)
    PublikationsdauerFallNeu_Schnitt = Column(Float)
    PublikationsdauerFallNeu_Median = Column(Float)
    PublikationsdauerFallNeu_StdAbw = Column(Float)
    PublikationsdauerFallNeu_Fallbasis = Column(Integer)
    DatenstandTag_Max = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A00_A04 = Column(Integer)
    MeldeTag_AnzahlFall_AG_A00_A04 = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A00_A04 = Column(Integer)
    MeldeTag_AnzahlTodesfall_AG_A00_A04 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A00_A04 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFall_AG_A00_A04 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A00_A04 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfall_AG_A00_A04 = Column(Integer)
    AnzahlFall_AG_A00_A04 = Column(Integer)
    AnzahlFallNeu_AG_A00_A04 = Column(Integer)
    AnzahlTodesfall_AG_A00_A04 = Column(Integer)
    AnzahlTodesfallNeu_AG_A00_A04 = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A05_A14 = Column(Integer)
    MeldeTag_AnzahlFall_AG_A05_A14 = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A05_A14 = Column(Integer)
    MeldeTag_AnzahlTodesfall_AG_A05_A14 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A05_A14 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFall_AG_A05_A14 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A05_A14 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfall_AG_A05_A14 = Column(Integer)
    AnzahlFall_AG_A05_A14 = Column(Integer)
    AnzahlFallNeu_AG_A05_A14 = Column(Integer)
    AnzahlTodesfall_AG_A05_A14 = Column(Integer)
    AnzahlTodesfallNeu_AG_A05_A14 = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A15_A34 = Column(Integer)
    MeldeTag_AnzahlFall_AG_A15_A34 = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A15_A34 = Column(Integer)
    MeldeTag_AnzahlTodesfall_AG_A15_A34 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A15_A34 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFall_AG_A15_A34 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A15_A34 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfall_AG_A15_A34 = Column(Integer)
    AnzahlFall_AG_A15_A34 = Column(Integer)
    AnzahlFallNeu_AG_A15_A34 = Column(Integer)
    AnzahlTodesfall_AG_A15_A34 = Column(Integer)
    AnzahlTodesfallNeu_AG_A15_A34 = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A35_A59 = Column(Integer)
    MeldeTag_AnzahlFall_AG_A35_A59 = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A35_A59 = Column(Integer)
    MeldeTag_AnzahlTodesfall_AG_A35_A59 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A35_A59 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFall_AG_A35_A59 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A35_A59 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfall_AG_A35_A59 = Column(Integer)
    AnzahlFall_AG_A35_A59 = Column(Integer)
    AnzahlFallNeu_AG_A35_A59 = Column(Integer)
    AnzahlTodesfall_AG_A35_A59 = Column(Integer)
    AnzahlTodesfallNeu_AG_A35_A59 = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A60_A79 = Column(Integer)
    MeldeTag_AnzahlFall_AG_A60_A79 = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A60_A79 = Column(Integer)
    MeldeTag_AnzahlTodesfall_AG_A60_A79 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A60_A79 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFall_AG_A60_A79 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A60_A79 = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfall_AG_A60_A79 = Column(Integer)
    AnzahlFall_AG_A60_A79 = Column(Integer)
    AnzahlFallNeu_AG_A60_A79 = Column(Integer)
    AnzahlTodesfall_AG_A60_A79 = Column(Integer)
    AnzahlTodesfallNeu_AG_A60_A79 = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A80Plus = Column(Integer)
    MeldeTag_AnzahlFall_AG_A80Plus = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A80Plus = Column(Integer)
    MeldeTag_AnzahlTodesfall_AG_A80Plus = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A80Plus = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFall_AG_A80Plus = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A80Plus = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfall_AG_A80Plus = Column(Integer)

    AnzahlFall_AG_A80Plus = Column(Integer)
    AnzahlFallNeu_AG_A80Plus = Column(Integer)
    AnzahlTodesfall_AG_A80Plus = Column(Integer)
    AnzahlTodesfallNeu_AG_A80Plus = Column(Integer)
    # Einwohner= Column(Integer)
    InzidenzFallNeu = Column(Float)

    # Einwohner_AG_A00_A04= Column(Integer)
    InzidenzFallNeu_AG_A00_A04 = Column(Float)
    # Einwohner_AG_A05_A14= Column(Integer)
    InzidenzFallNeu_AG_A05_A14 = Column(Float)
    # Einwohner_AG_A15_A34= Column(Integer)
    InzidenzFallNeu_AG_A15_A34 = Column(Float)
    # Einwohner_AG_A35_A59= Column(Integer)
    InzidenzFallNeu_AG_A35_A59 = Column(Float)
    # Einwohner_AG_A60_A79= Column(Integer)
    InzidenzFallNeu_AG_A60_A79 = Column(Float)
    # Einwohner_AG_A80Plus= Column(Integer)
    InzidenzFallNeu_AG_A80Plus = Column(Float)

    MeldeTag_AnzahlFallNeu_Gestern = Column(Integer)
    MeldeTag_AnzahlFall_Gestern = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_Gestern = Column(Integer)
    MeldeTag_AnzahlTodesfall_Gestern = Column(Integer)

    MeldeTag_AnzahlFallNeu_AG_A00_A04_Gestern = Column(Integer)
    MeldeTag_AnzahlFall_AG_A00_A04_Gestern = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A00_A04_Gestern = Column(Integer)
    MeldeTag_AnzahlTodesfall_AG_A00_A04_Gestern = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A05_A14_Gestern = Column(Integer)
    MeldeTag_AnzahlFall_AG_A05_A14_Gestern = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A05_A14_Gestern = Column(Integer)
    MeldeTag_AnzahlTodesfall_AG_A05_A14_Gestern = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A15_A34_Gestern = Column(Integer)
    MeldeTag_AnzahlFall_AG_A15_A34_Gestern = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A15_A34_Gestern = Column(Integer)
    MeldeTag_AnzahlTodesfall_AG_A15_A34_Gestern = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A35_A59_Gestern = Column(Integer)
    MeldeTag_AnzahlFall_AG_A35_A59_Gestern = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A35_A59_Gestern = Column(Integer)
    MeldeTag_AnzahlTodesfall_AG_A35_A59_Gestern = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A60_A79_Gestern = Column(Integer)
    MeldeTag_AnzahlFall_AG_A60_A79_Gestern = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A60_A79_Gestern = Column(Integer)
    MeldeTag_AnzahlTodesfall_AG_A60_A79_Gestern = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A80Plus_Gestern = Column(Integer)
    MeldeTag_AnzahlFall_AG_A80Plus_Gestern = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A80Plus_Gestern = Column(Integer)
    MeldeTag_AnzahlTodesfall_AG_A80Plus_Gestern = Column(Integer)

    MeldeTag_Vor7Tagen_AnzahlFallNeu_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFall_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfall_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A00_A04_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFall_AG_A00_A04_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A00_A04_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfall_AG_A00_A04_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A05_A14_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFall_AG_A05_A14_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A05_A14_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfall_AG_A05_A14_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A15_A34_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFall_AG_A15_A34_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A15_A34_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfall_AG_A15_A34_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A35_A59_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFall_AG_A35_A59_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A35_A59_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfall_AG_A35_A59_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A60_A79_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFall_AG_A60_A79_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A60_A79_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfall_AG_A60_A79_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A80Plus_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFall_AG_A80Plus_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A80Plus_Vor8Tagen = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfall_AG_A80Plus_Vor8Tagen = Column(Integer)

    InzidenzTodesfallNeu = Column(Float)
    MeldeTag_InzidenzFall = Column(Float)
    MeldeTag_InzidenzTodesfall = Column(Float)
    MeldeTag_Fallsterblichkeit_Prozent = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzFall = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzTodesfall = Column(Float)
    MeldeTag_Vor7Tagen_Fallsterblichkeit_Prozent = Column(Float)
    InzidenzFall = Column(Float)
    InzidenzTodesfall = Column(Float)
    Fallsterblichkeit_Prozent = Column(Float)

    MeldeTag_InzidenzFall_AG_A00_A04 = Column(Float)
    MeldeTag_InzidenzTodesfall_AG_A00_A04 = Column(Float)
    MeldeTag_Fallsterblichkeit_Prozent_AG_A00_A04 = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzFall_AG_A00_A04 = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzTodesfall_AG_A00_A04 = Column(Float)
    MeldeTag_Vor7Tagen_Fallsterblichkeit_Prozent_AG_A00_A04 = Column(Float)
    InzidenzFall_AG_A00_A04 = Column(Float)
    InzidenzTodesfall_AG_A00_A04 = Column(Float)
    Fallsterblichkeit_Prozent_AG_A00_A04 = Column(Float)
    MeldeTag_InzidenzFall_AG_A05_A14 = Column(Float)
    MeldeTag_InzidenzTodesfall_AG_A05_A14 = Column(Float)
    MeldeTag_Fallsterblichkeit_Prozent_AG_A05_A14 = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzFall_AG_A05_A14 = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzTodesfall_AG_A05_A14 = Column(Float)
    MeldeTag_Vor7Tagen_Fallsterblichkeit_Prozent_AG_A05_A14 = Column(Float)
    InzidenzFall_AG_A05_A14 = Column(Float)
    InzidenzTodesfall_AG_A05_A14 = Column(Float)
    Fallsterblichkeit_Prozent_AG_A05_A14 = Column(Float)
    MeldeTag_InzidenzFall_AG_A15_A34 = Column(Float)
    MeldeTag_InzidenzTodesfall_AG_A15_A34 = Column(Float)
    MeldeTag_Fallsterblichkeit_Prozent_AG_A15_A34 = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzFall_AG_A15_A34 = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzTodesfall_AG_A15_A34 = Column(Float)
    MeldeTag_Vor7Tagen_Fallsterblichkeit_Prozent_AG_A15_A34 = Column(Float)
    InzidenzFall_AG_A15_A34 = Column(Float)
    InzidenzTodesfall_AG_A15_A34 = Column(Float)
    Fallsterblichkeit_Prozent_AG_A15_A34 = Column(Float)
    MeldeTag_InzidenzFall_AG_A35_A59 = Column(Float)
    MeldeTag_InzidenzTodesfall_AG_A35_A59 = Column(Float)
    MeldeTag_Fallsterblichkeit_Prozent_AG_A35_A59 = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzFall_AG_A35_A59 = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzTodesfall_AG_A35_A59 = Column(Float)
    MeldeTag_Vor7Tagen_Fallsterblichkeit_Prozent_AG_A35_A59 = Column(Float)
    InzidenzFall_AG_A35_A59 = Column(Float)
    InzidenzTodesfall_AG_A35_A59 = Column(Float)
    Fallsterblichkeit_Prozent_AG_A35_A59 = Column(Float)
    MeldeTag_InzidenzFall_AG_A60_A79 = Column(Float)
    MeldeTag_InzidenzTodesfall_AG_A60_A79 = Column(Float)
    MeldeTag_Fallsterblichkeit_Prozent_AG_A60_A79 = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzFall_AG_A60_A79 = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzTodesfall_AG_A60_A79 = Column(Float)
    MeldeTag_Vor7Tagen_Fallsterblichkeit_Prozent_AG_A60_A79 = Column(Float)
    InzidenzFall_AG_A60_A79 = Column(Float)
    InzidenzTodesfall_AG_A60_A79 = Column(Float)
    Fallsterblichkeit_Prozent_AG_A60_A79 = Column(Float)
    MeldeTag_InzidenzFall_AG_A80Plus = Column(Float)
    MeldeTag_InzidenzTodesfall_AG_A80Plus = Column(Float)
    MeldeTag_Fallsterblichkeit_Prozent_AG_A80Plus = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzFall_AG_A80Plus = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzTodesfall_AG_A80Plus = Column(Float)
    MeldeTag_Vor7Tagen_Fallsterblichkeit_Prozent_AG_A80Plus = Column(Float)
    InzidenzFall_AG_A80Plus = Column(Float)
    InzidenzTodesfall_AG_A80Plus = Column(Float)
    Fallsterblichkeit_Prozent_AG_A80Plus = Column(Float)

    MeldeTag_InzidenzFall_Gestern = Column(Float)
    MeldeTag_InzidenzTodesfall_Gestern = Column(Float)
    MeldeTag_Fallsterblichkeit_Prozent_Gestern = Column(Float)

    MeldeTag_InzidenzFall_AG_A00_A04_Gestern = Column(Float)
    MeldeTag_InzidenzTodesfall_AG_A00_A04_Gestern = Column(Float)
    MeldeTag_Fallsterblichkeit_Prozent_AG_A00_A04_Gestern = Column(Float)
    MeldeTag_InzidenzFall_AG_A05_A14_Gestern = Column(Float)
    MeldeTag_InzidenzTodesfall_AG_A05_A14_Gestern = Column(Float)
    MeldeTag_Fallsterblichkeit_Prozent_AG_A05_A14_Gestern = Column(Float)
    MeldeTag_InzidenzFall_AG_A15_A34_Gestern = Column(Float)
    MeldeTag_InzidenzTodesfall_AG_A15_A34_Gestern = Column(Float)
    MeldeTag_Fallsterblichkeit_Prozent_AG_A15_A34_Gestern = Column(Float)
    MeldeTag_InzidenzFall_AG_A35_A59_Gestern = Column(Float)
    MeldeTag_InzidenzTodesfall_AG_A35_A59_Gestern = Column(Float)
    MeldeTag_Fallsterblichkeit_Prozent_AG_A35_A59_Gestern = Column(Float)
    MeldeTag_InzidenzFall_AG_A60_A79_Gestern = Column(Float)
    MeldeTag_InzidenzTodesfall_AG_A60_A79_Gestern = Column(Float)
    MeldeTag_Fallsterblichkeit_Prozent_AG_A60_A79_Gestern = Column(Float)
    MeldeTag_InzidenzFall_AG_A80Plus_Gestern = Column(Float)
    MeldeTag_InzidenzTodesfall_AG_A80Plus_Gestern = Column(Float)
    MeldeTag_Fallsterblichkeit_Prozent_AG_A80Plus_Gestern = Column(Float)

    MeldeTag_Vor7Tagen_InzidenzFall_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzTodesfall_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_Fallsterblichkeit_Prozent_Vor8Tagen = Column(Float)

    MeldeTag_Vor7Tagen_InzidenzFall_AG_A00_A04_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzTodesfall_AG_A00_A04_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_Fallsterblichkeit_Prozent_AG_A00_A04_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzFall_AG_A05_A14_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzTodesfall_AG_A05_A14_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_Fallsterblichkeit_Prozent_AG_A05_A14_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzFall_AG_A15_A34_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzTodesfall_AG_A15_A34_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_Fallsterblichkeit_Prozent_AG_A15_A34_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzFall_AG_A35_A59_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzTodesfall_AG_A35_A59_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_Fallsterblichkeit_Prozent_AG_A35_A59_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzFall_AG_A60_A79_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzTodesfall_AG_A60_A79_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_Fallsterblichkeit_Prozent_AG_A60_A79_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzFall_AG_A80Plus_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzTodesfall_AG_A80Plus_Vor8Tagen = Column(Float)
    MeldeTag_Vor7Tagen_Fallsterblichkeit_Prozent_AG_A80Plus_Vor8Tagen = Column(Float)

    MeldeTag_AnzahlFallNeu_7TageSumme = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_7TageSumme = Column(Integer)
    AnzahlFallNeu_7TageSumme = Column(Integer)
    AnzahlFallNeu_7TageSumme_Trend = Column(Float)
    AnzahlFallNeu_7TageSumme_7_Tage_davor = Column(Integer)
    AnzahlTodesfallNeu_7TageSumme = Column(Integer)
    AnzahlTodesfallNeu_7TageSumme_Trend = Column(Float)
    AnzahlTodesfallNeu_7TageSumme_7_Tage_davor = Column(Integer)
    AnzahlGenesenNeu_7TageSumme = Column(Integer)
    AnzahlGenesenNeu_7TageSumme_Trend = Column(Float)

    MeldeTag_AnzahlFallNeu_AG_A00_A04_7TageSumme = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A00_A04_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A00_A04_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A00_A04_7TageSumme = Column(Integer)
    AnzahlFallNeu_AG_A00_A04_7TageSumme = Column(Integer)
    AnzahlFallNeu_AG_A00_A04_7TageSumme_Trend = Column(Float)
    AnzahlTodesfallNeu_AG_A00_A04_7TageSumme = Column(Integer)
    AnzahlTodesfallNeu_AG_A00_A04_7TageSumme_Trend = Column(Float)
    MeldeTag_AnzahlFallNeu_AG_A05_A14_7TageSumme = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A05_A14_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A05_A14_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A05_A14_7TageSumme = Column(Integer)
    AnzahlFallNeu_AG_A05_A14_7TageSumme = Column(Integer)
    AnzahlFallNeu_AG_A05_A14_7TageSumme_Trend = Column(Float)
    AnzahlTodesfallNeu_AG_A05_A14_7TageSumme = Column(Integer)
    AnzahlTodesfallNeu_AG_A05_A14_7TageSumme_Trend = Column(Float)
    MeldeTag_AnzahlFallNeu_AG_A15_A34_7TageSumme = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A15_A34_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A15_A34_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A15_A34_7TageSumme = Column(Integer)
    AnzahlFallNeu_AG_A15_A34_7TageSumme = Column(Integer)
    AnzahlFallNeu_AG_A15_A34_7TageSumme_Trend = Column(Float)
    AnzahlTodesfallNeu_AG_A15_A34_7TageSumme = Column(Integer)
    AnzahlTodesfallNeu_AG_A15_A34_7TageSumme_Trend = Column(Float)
    MeldeTag_AnzahlFallNeu_AG_A35_A59_7TageSumme = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A35_A59_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A35_A59_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A35_A59_7TageSumme = Column(Integer)
    AnzahlFallNeu_AG_A35_A59_7TageSumme = Column(Integer)
    AnzahlFallNeu_AG_A35_A59_7TageSumme_Trend = Column(Float)
    AnzahlTodesfallNeu_AG_A35_A59_7TageSumme = Column(Integer)
    AnzahlTodesfallNeu_AG_A35_A59_7TageSumme_Trend = Column(Float)
    MeldeTag_AnzahlFallNeu_AG_A60_A79_7TageSumme = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A60_A79_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A60_A79_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A60_A79_7TageSumme = Column(Integer)
    AnzahlFallNeu_AG_A60_A79_7TageSumme = Column(Integer)
    AnzahlFallNeu_AG_A60_A79_7TageSumme_Trend = Column(Float)
    AnzahlTodesfallNeu_AG_A60_A79_7TageSumme = Column(Integer)
    AnzahlTodesfallNeu_AG_A60_A79_7TageSumme_Trend = Column(Float)
    MeldeTag_AnzahlFallNeu_AG_A80Plus_7TageSumme = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A80Plus_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A80Plus_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A80Plus_7TageSumme = Column(Integer)
    AnzahlFallNeu_AG_A80Plus_7TageSumme = Column(Integer)
    AnzahlFallNeu_AG_A80Plus_7TageSumme_Trend = Column(Float)
    AnzahlTodesfallNeu_AG_A80Plus_7TageSumme = Column(Integer)
    AnzahlTodesfallNeu_AG_A80Plus_7TageSumme_Trend = Column(Float)

    InzidenzFallNeu_7TageSumme = Column(Float)
    InzidenzFallNeu_7TageSumme_Trend = Column(Float)
    InzidenzFallNeu_7TageSumme_7_Tage_davor = Column(Float)
    InzidenzFallNeu_7TageSumme_Trend_Spezial = Column(Float)
    InzidenzFallNeu_7TageSumme_R = Column(Float)
    InzidenzFallNeu_Prognose_1_Wochen = Column(Float)
    InzidenzFallNeu_Prognose_2_Wochen = Column(Float)
    InzidenzFallNeu_Prognose_4_Wochen = Column(Float)
    InzidenzFallNeu_Prognose_8_Wochen = Column(Float)
    InzidenzFallNeu_Tage_bis_50 = Column(Float)
    InzidenzFallNeu_Tage_bis_100 = Column(Float)
    Kontaktrisiko = Column(Float)

    InzidenzFallNeu_AG_A00_A04_7TageSumme = Column(Float)
    InzidenzFallNeu_AG_A00_A04_7TageSumme_Trend = Column(Float)
    InzidenzFallNeu_AG_A05_A14_7TageSumme = Column(Float)
    InzidenzFallNeu_AG_A05_A14_7TageSumme_Trend = Column(Float)
    InzidenzFallNeu_AG_A15_A34_7TageSumme = Column(Float)
    InzidenzFallNeu_AG_A15_A34_7TageSumme_Trend = Column(Float)
    InzidenzFallNeu_AG_A35_A59_7TageSumme = Column(Float)
    InzidenzFallNeu_AG_A35_A59_7TageSumme_Trend = Column(Float)
    InzidenzFallNeu_AG_A60_A79_7TageSumme = Column(Float)
    InzidenzFallNeu_AG_A60_A79_7TageSumme_Trend = Column(Float)
    InzidenzFallNeu_AG_A80Plus_7TageSumme = Column(Float)
    InzidenzFallNeu_AG_A80Plus_7TageSumme_Trend = Column(Float)

    MeldeTag_AnzahlFallNeu_Gestern_7TageSumme = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_Gestern_7TageSumme = Column(Integer)

    MeldeTag_AnzahlFallNeu_AG_A00_A04_Gestern_7TageSumme = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A00_A04_Gestern_7TageSumme = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A05_A14_Gestern_7TageSumme = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A05_A14_Gestern_7TageSumme = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A15_A34_Gestern_7TageSumme = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A15_A34_Gestern_7TageSumme = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A35_A59_Gestern_7TageSumme = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A35_A59_Gestern_7TageSumme = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A60_A79_Gestern_7TageSumme = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A60_A79_Gestern_7TageSumme = Column(Integer)
    MeldeTag_AnzahlFallNeu_AG_A80Plus_Gestern_7TageSumme = Column(Integer)
    MeldeTag_AnzahlTodesfallNeu_AG_A80Plus_Gestern_7TageSumme = Column(Integer)

    MeldeTag_Vor7Tagen_AnzahlFallNeu_Vor8Tagen_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_Vor8Tagen_7TageSumme = Column(Integer)

    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A00_A04_Vor8Tagen_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A00_A04_Vor8Tagen_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A05_A14_Vor8Tagen_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A05_A14_Vor8Tagen_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A15_A34_Vor8Tagen_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A15_A34_Vor8Tagen_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A35_A59_Vor8Tagen_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A35_A59_Vor8Tagen_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A60_A79_Vor8Tagen_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A60_A79_Vor8Tagen_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlFallNeu_AG_A80Plus_Vor8Tagen_7TageSumme = Column(Integer)
    MeldeTag_Vor7Tagen_AnzahlTodesfallNeu_AG_A80Plus_Vor8Tagen_7TageSumme = Column(Integer)
    InzidenzTodesfallNeu_7TageSumme = Column(Float)
    InzidenzTodesfallNeu_7TageSumme_Trend = Column(Float)
    InzidenzTodesfallNeu_7TageSumme_7_Tage_davor = Column(Float)
    InzidenzTodesfallNeu_7TageSumme_Trend_Spezial = Column(Float)
    DatenstandTag_Diff = Column(Integer)
    MeldeTag_InzidenzFallNeu_Gestern_7TageSumme = Column(Float)
    AnzahlFallNeu_7TageSumme_Dropped = Column(Integer)
    ProzentFallNeu_7TageSumme_Dropped = Column(Float)
    MeldeTag_Vor7Tagen_InzidenzFallNeu_Vor8Tagen_7TageSumme = Column(Float)
    MeldeTag_InzidenzFallNeu_Trend = Column(Float)
    MeldeTag_InzidenzFallNeu_R = Column(Float)
    MeldeTag_InzidenzFallNeu_Prognose_4_Wochen = Column(Float)
    PublikationsdauerFallNeu_Min_Neg = Column(Integer)

    # up
    Landkreis_ID = Column(Integer, ForeignKey("landkreise.ID"))
    Landkreis = relationship("Landkreis", back_populates="Daten")
    """
    Altersgruppe_ID = Column(Integer, ForeignKey("altersgruppen.ID"))
    Altersgruppe = relationship("Altersgruppe", back_populates="Landkreis_faelle")
    """


"""
class Altersgruppe(Base):
    __tablename__ = "altersgruppen"
    ID = Column(Integer, primary_key=True, index=True)
    Name = Column(String, index=True)

    # down

    Bundesland_faelle = relationship(
        "Bundesland_Daten", back_populates="Altersgruppe"
    )

    Landkreis_faelle = relationship(
        "Landkreis_Daten", back_populates="Altersgruppe"
    )

    # alle_faelle = relationship("Fall_Daten_Taeglich", back_populates="Altersgruppe")
"""

"""
class Fall_Daten_Taeglich(Base):
    __tablename__ = "faelle_daten_taeglich"
    # __table_args__ = (UniqueConstraint("name", "typ", name="_lk_name_typ_uc"),)
    ID = Column(Integer, primary_key=True, index=True)

    Geschlecht = Column(String)
    MeldeDatum = Column(Integer, nullable=False, index=True)
    AnzahlFall = Column(Integer, nullable=False)
    AnzahlTodesfall = Column(Integer, nullable=False)
    AnzahlGenesen = Column(Integer, nullable=False)
    # up
    Altersgruppe_id = Column(Integer, ForeignKey("altersgruppen.id"))
    Altersgruppe = relationship("Altersgruppe", back_populates="alle_faelle")

    landkreis_id = Column(Integer, ForeignKey("landkreise.ID"))
    landkreis = relationship("Landkreis", back_populates="alle_faelle")

    bundesland_id = Column(Integer, ForeignKey("bundeslaender.ID"))
    bundesland = relationship("Bundesland", back_populates="alle_faelle")

    bundesland_meldedatum_id = Column(
        Integer, ForeignKey("bundeslaender_daten.ID")
    )
    bundesland_meldedatum = relationship(
        "Bundesland_Daten", back_populates="Zugehoerige_faelle"
    )
"""

"""
class Inserted_csv_File(Base):

    __tablename__ = "inserted_csv_files"
    # __table_args__ = (UniqueConstraint("name", "typ", name="_lk_name_typ_uc"),)
    ID = Column(Integer, primary_key=True, index=True)
    data_type = Column(String)
    date = Column(String)
    md5sum = Column(String)
    file_path = Column(String)
    date_file_processed = Column(String)
"""
